
# Service
serviceName : Todo
serviceUrl : http://hexagonkt.com
serviceDescription : A Todo Backend with Hexagon
serviceLongDescription : >
  A Todo API created for http://www.todobackend.com/index.html to
  showcase Hexagons functionality.

# HTTP Server
bindPort : 2010
bindAddress : 0.0.0.0

# Storage
mongoDbUrl: mongodb://localhost:27017/todo
